const LocalConst = {
    COMMENT_NAME_INFO: '必须填写昵称或姓名',
    COMMENT_EMAIL_INFO: '必须填写电子邮箱地址',
    COMMENT_EMAIL_LEGAL_INFO: '邮箱地址不合法',
    COMMENT_CONTENT_INFO: '必须填写评论内容',
    COMMENT_SUBMIT_ERROR: '提交失败，请重试！',
    COMMENT_CONTENT_LEGAL_INFO: '提交失败,您的输入内容不符合规则！',

    LOGIN_USERNAME_INFO: '必须填写用户名',
    LOGIN_PASSWORD_INFO: '请填写密码',
    LOGIN_SUBMIT_ERROR: '登录失败，请重新登录',
    LOGIN_SUBMIT_INFO: '用户名或者密码错误，请重试',
    LOGIN_SUBMIT_SUCCESS: '登录成功',
    CLICK_TO_REFRESH: '点击以刷新页面',
    LOGOUT_SUCCESS_REFRESH: '退出成功，正在刷新当前页面',

    LOGOUT_ERROR: '退出失败，请重试',
    LOGOUT_SUCCESS: '退出成功',

    SUBMIT_PASSWORD_INFO: '密码错误，请重试',
    COMMENT_TITLE: '评论通知',
    LOGIN_TITLE: '登录通知',
    ChANGYAN_APP_KEY: '',
    CHANGYAN_CONF: '',

    COMMENT_SYSTEM: '0',
    COMMENT_SYSTEM_ROOT: '0',
    COMMENT_SYSTEM_CHANGYAN: '1',
    COMMENT_SYSTEM_OTHERS: '2',
    EMOJI: '表情',
    IS_PJAX: '1',
    IS_PAJX_COMMENT: '1',
    BASE_SCRIPT_URL: 'http://jijianblog.com/usr/themes/handsome/',
    BLOG_URL: 'http://jijianblog.com/',
    BLOG_URL_PHP: 'http://jijianblog.com/index.php/',
    THEME_COLOR: '7',
    THEME_HEADER_FIX: '1',
    THEME_ASIDE_FIX: '1',
    THEME_ASIDE_FOLDED: '',
    THEME_ASIDE_DOCK: '',
    THEME_CONTAINER_BOX: '1',
    THEME_HIGHLIGHT_CODE: '1',
    THEME_TOC: '1',
    TOC_TITLE: '文章目录',
    HEADER_FIX: '固定头部',
    ASIDE_FIX: '固定导航',
    ASIDE_FOLDED: '折叠导航',
    ASIDE_DOCK: '置顶导航',
    CONTAINER_BOX: '盒子模型',
    OFF_SCROLL_HEIGHT: '50',
    COMMENT_REJECT_PLACEHOLDER: '居然什么也不说，哼',
    COMMENT_PLACEHOLDER: '说点什么吧……',
    SHOW_SETTING_BUTTON: '',
    THEME_VERSION: '5.3.120190915221',

    OPERATION_NOTICE: '操作通知',
    SCREENSHOT_BEGIN: '正在生成当前页面截图……',
    SCREENSHOT_NOTICE: '点击顶部下载按钮保存当前卡片',
    SCREENSHORT_ERROR: '由于图片跨域原因导致截图失败',
    SCREENSHORT_SUCCESS: '截图成功',
    MUSIC_NOTICE: '播放通知',
    MUSIC_FAILE: '当前音乐地址无效，自动为您播放下一首',
    MUSIC_FAILE_END: '当前音乐地址无效',
    MUSIC_LIST_SUCCESS: '歌单歌曲加载成功',
    CDN_NAME: ''
};
